package:
  name: unifrac
  version: "0.9.1"

source:
  git_url: https://github.com/biocore/unifrac.git
  git_rev: 0.9.1

build:
  # noarch_python: True
  preserve_egg_dir: True
  number: 1

requirements:
  build:
    - python 3.5*
    - gcc  # [not osx]
    - llvm  # [osx]
    - hdf5 ==1.8.17
    - cython
    - numpy

  run:
    - python 3.5*
    - libgcc  # [not osx]
    - hdf5 ==1.8.17
    - h5py
    - cython
    - biom-format
    - scikit-bio

test:
  # Python imports
  imports:
    - unifrac
  
  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - ssu --help

about:
  license: BSD License
  summary: 'UniFrac'
